# Site settings
title: Jakiro’s Blog
SEOTitle: Jakiro Feng
header-img: img/basicIMG/home_bg_monet.jpg
email: jakirofeng@qq.com
description: "My prey is near."
keyword: "FengWei, 游戏策划, 游戏开发"
url: "http://jakirowarden.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/jakirowarden/jakirowarden.github.io.git" # you code repository

plugins:
- jekyll-paginate
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "努力努力再努力！"
sidebar-avatar: /img/basicIMG/home_sidebar_avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`






# SNS settings
RSS: false
# weibo_username:    
#zhihu_username:     
#github_username:    jakirowarden
#facebook_username:  
#jianshu_username:   
#twitter_username:   




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: jakirofeng

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 02e47cf222f1e1ce210f                           #生成的clientID
  clientSecret: abb16224c07a32efe160009b1f7798c00975b75b    #生成的clientSecret
  repo: jakirowarden.github.io    #仓库名称
  owner: jakirowarden    #github用户名
  admin: jakirowarden
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings

# Google Analytics
ga_track_id: 'UA-161702697-1'            # Format: UA-xxxxxx-xx
ga_domain: auto             # 默认的是 auto




# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    # {
    #     title: "WY",
    #     href: "http://zhengwuyang.com"
    # },{
    #     title: "简书·BY",
    #     href: "http://www.jianshu.com/u/e71990ada2fd"
    # },{
    #     title: "Apple",
    #     href: "https://apple.com"
    # },{
    #     title: "Apple Developer",
    #     href: "https://developer.apple.com/"
    # }
]
